nombre = input("¿Cual es  su nombre?: ")
apellido = input("¿Cual es su apellido?: ")
codigo_seccion = input("I¿Cual es su código de sección?: ")
sede = input("¿Cual es su sede?: ")
print("Información del estudiante:")
print("Nombre: ", nombre)
print("Apellido: ", apellido)
print("Código de sección: ", codigo_seccion)
print("Sede: ", sede)